// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef hello_h
#define hello_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>

/**
   first fluid attempt
*/
class hello {
public:
  hello(string title,string msg);
  hello();
  Fl_Double_Window* make_window(string title, string msg);
  Fl_Double_Window *hello_win;
  hello *hello_lbl;
private:
  inline void cb_OK_i(Fl_Return_Button*, void*);
  static void cb_OK(Fl_Return_Button*, void*);
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
public:
  void show(int argc, char **argv);
};
#endif
